In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# Load CSV
df = pd.read_csv("athlete_events.csv")
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [4]:
df.dropna(subset= ['Medal'], inplace=True)

In [5]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
37,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze
38,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39783 entries, 3 to 271103
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      39783 non-null  int64
 1   Name    39783 non-null  object
 2   Sex     39783 non-null  object
 3   Age     39051 non-null  float64
 4   Height  31072 non-null  float64
 5   Weight  30456 non-null  float64
 6   Team    39783 non-null  object
 7   NOC     39783 non-null  object
 8   Games   39783 non-null  object
 9   Year    39783 non-null  int64
 10  Season  39783 non-null  object
 11  City    39783 non-null  object
 12  Sport   39783 non-null  object
 13  Event   39783 non-null  object
 14  Medal   39783 non-null  object
dtypes: float64(3), int64(2), object(10)
memory usage: 4.9+ MB

In [7]:
Summer_df = df.loc[df["Season"] == "Summer", :]

In [8]:
Summer_df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
37,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze
38,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
42,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Team All-Around,Gold

In [9]:
Summer_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34088 entries, 3 to 271103
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      34088 non-null  int64
 1   Name    34088 non-null  object
 2   Sex     34088 non-null  object
 3   Age     33367 non-null  float64
 4   Height  26098 non-null  float64
 5   Weight  25598 non-null  float64
 6   Team    34088 non-null  object
 7   NOC     34088 non-null  object
 8   Games   34088 non-null  object
 9   Year    34088 non-null  int64
 10  Season  34088 non-null  object
 11  City    34088 non-null  object
 12  Sport   34088 non-null  object
 13  Event   34088 non-null  object
 14  Medal   34088 non-null  object
dtypes: float64(3), int64(2), object(10)
memory usage: 4.2+ MB

In [10]:
Summer_df.describe()

                  ID           Age        Height        Weight          Year
count   34088.000000  33367.000000  26098.000000  25598.000000  34088.000000
mean    69317.155363     25.901579    177.938156     73.953388   1971.878667
std     38927.611363      6.074975     11.216148     15.356776     34.745000
min         4.000000     10.000000    136.000000     28.000000   1896.000000
25%     36065.000000     22.000000    170.000000     63.000000   1948.000000
50%     69191.000000     25.000000    178.000000     73.000000   1980.000000
75%    103371.250000     29.000000    185.000000     83.000000   2000.000000
max    135563.000000     73.000000    223.000000    182.000000   2016.000000

In [11]:
# Gold medals won
gold_df = Summer_df.loc[df["Medal"] == "Gold", [
    "ID", "Name", "Sex", "Age", "Height", "Weight", "Team", "Games", "City", "Sport", "Event", "Medal"]]

gold_df.head()

,ID,Name,Sex,Age,Height,Weight,Team,Games,City,Sport,Event,Medal
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
42,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,London,Gymnastics,Gymnastics Men's Team All-Around,Gold
44,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,London,Gymnastics,Gymnastics Men's Horse Vault,Gold
48,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,London,Gymnastics,Gymnastics Men's Pommelled Horse,Gold
79,21,Ragnhild Margrethe Aamodt,F,27.0,163.0,NaN,Norway,2008 Summer,Beijing,Handball,Handball Women's Handball,Gold

In [12]:
# Silver medals won
silver_df = Summer_df.loc[df["Medal"] == "Silver", [
   "ID", "Name", "Sex", "Age", "Height", "Weight", "Team", "Games", "City", "Sport", "Event", "Medal"]]
silver_df.head()

,ID,Name,Sex,Age,Height,Weight,Team,Games,City,Sport,Event,Medal
86,25,Alf Lied Aanning,M,24.0,NaN,NaN,Norway,1920 Summer,Antwerpen,Gymnastics,"Gymnastics Men's Team All-Around, Free System",Silver
92,30,Pepijn Aardewijn,M,26.0,189.0,72.0,Netherlands,1996 Summer,Atlanta,Rowing,Rowing Men's Lightweight Double Sculls,Silver
106,38,Karl Jan Aas,M,20.0,NaN,NaN,Norway,1920 Summer,Antwerpen,Gymnastics,"Gymnastics Men's Team All-Around, Free System",Silver
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22.0,179.0,80.0,Russia,2008 Summer,Beijing,Athletics,Athletics Women's Javelin Throw,Silver
175,73,Luc Abalo,M,31.0,182.0,86.0,France,2016 Summer,Rio de Janeiro,Handball,Handball Men's Handball,Silver

In [13]:
### Bronze Medals Won
bronze_df = Summer_df.loc[df["Medal"] == "Bronze", [
   "ID", "Name", "Sex", "Age", "Height", "Weight", "Team", "Games", "City", "Sport", "Event", "Medal"]]
bronze_df.head()

,ID,Name,Sex,Age,Height,Weight,Team,Games,City,Sport,Event,Medal
37,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,1920 Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze
38,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,1920 Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
50,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,1952 Summer,Helsinki,Gymnastics,Gymnastics Men's Team All-Around,Bronze
91,29,Willemien Aardenburg,F,22.0,NaN,NaN,Netherlands,1988 Summer,Seoul,Hockey,Hockey Women's Hockey,Bronze

In [14]:
Total_Medals = Summer_df['Team'].value_counts()
Total_Medals.head(25)

United States    4686
Soviet Union     2061
Germany          1687
Great Britain    1598
France           1408
Italy            1384
Australia        1290
Hungary          1123
Sweden           1006
Russia            894
Netherlands       866
Japan             848
East Germany      841
China             831
Canada            668
Romania           651
Denmark           548
Poland            536
South Korea       506
West Germany      502
Spain             481
Norway            467
Finland           450
Brazil            449
Cuba              407
Name: Team, dtype: int64